#!/usr/bin/env node
/**
 * Keeps the README in sync with the repository and renders the GitHub Pages
 * site from it. Run with `npm run docs:build` (CI does this automatically).
 *
 * - Injects the Playwright screenshot gallery into the README.
 * - Injects the latest coverage summary into the README.
 * - Renders docs/index.html, which is published to GitHub Pages.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readmeFile = path.join(root, 'README.md');
const screenshotDir = path.join(root, 'docs', 'screenshots');
const coverageFile = path.join(root, 'coverage', 'coverage-summary.json');

const CAPTIONS = {
  '01-sign-in.png': 'Sign in or create a private, encrypted vault',
  '02-documents.png': 'Health, finance, professional and education documents stored encrypted',
  '03-grounded-answer.png': 'Answers are extracted from your documents and always cited',
  '04-refuses-outside-knowledge.png':
    'Questions your documents cannot answer are refused instead of guessed',
  '05-isolated-accounts.png': 'A second account can neither see nor query another user documents',
  '06-account-erased.png': 'One click erases the account and every stored document',
  '07-mobile-ask.png': 'Asking a question is a page of its own and the primary action on mobile',
  '08-mobile-documents.png':
    'Every page does one thing, with a thumb-friendly tab bar on small screens',
  '09-light-theme.png': 'A light theme for bright rooms, remembered across visits',
  '10-dark-theme.png': 'A dark theme, or simply follow the theme of the device',
};

function replaceSection(markdown, name, body) {
  const start = `<!-- ${name}:start -->`;
  const end = `<!-- ${name}:end -->`;
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  if (!pattern.test(markdown)) {
    throw new Error(`README is missing the ${name} markers`);
  }
  return markdown.replace(pattern, `${start}\n${body}\n${end}`);
}

function screenshotSection() {
  const files = fs.existsSync(screenshotDir)
    ? fs
        .readdirSync(screenshotDir)
        .filter((file) => file.endsWith('.png'))
        .sort()
    : [];
  if (files.length === 0) {
    return '_Screenshots are generated by `npm run test:e2e`._';
  }
  return files
    .map((file) => {
      const caption = CAPTIONS[file] ?? file.replace(/^\d+-|\.png$/g, '').replace(/-/g, ' ');
      return `### ${caption}\n\n![${caption}](docs/screenshots/${file})`;
    })
    .join('\n\n');
}

function coverageSection() {
  if (!fs.existsSync(coverageFile)) {
    return '_Run `npm run test:coverage` to generate the coverage summary._';
  }
  const { total } = JSON.parse(fs.readFileSync(coverageFile, 'utf8'));
  const rows = ['statements', 'branches', 'functions', 'lines']
    .map((metric) => `| ${metric} | ${total[metric].pct}% |`)
    .join('\n');
  return `| Metric | Coverage |\n| --- | --- |\n${rows}`;
}

function renderSite(markdown) {
  const html = marked.parse(markdown.replace(/docs\/screenshots\//g, 'screenshots/'), {
    async: false,
  });
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>baby-model &middot; a model that only knows your data</title>
    <link rel="stylesheet" href="site.css" />
  </head>
  <body>
    <main class="prose">
${html}
    </main>
  </body>
</html>
`;
}

const readme = fs.readFileSync(readmeFile, 'utf8');
const updated = replaceSection(
  replaceSection(readme, 'screenshots', screenshotSection()),
  'coverage',
  coverageSection(),
);
fs.writeFileSync(readmeFile, updated);
fs.writeFileSync(path.join(root, 'docs', 'index.html'), renderSite(updated));
process.stdout.write('README and docs/index.html updated\n');
